//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria_REST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VETERINARIAPROJECTEntities : DbContext
    {
        public VETERINARIAPROJECTEntities()
            : base("name=VETERINARIAPROJECTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CIRUGIA> CIRUGIAs { get; set; }
        public virtual DbSet<CONSULTAMEDICA> CONSULTAMEDICAs { get; set; }
        public virtual DbSet<DETALLESERVICIO> DETALLESERVICIOs { get; set; }
        public virtual DbSet<ESPECIALIZACION> ESPECIALIZACIONs { get; set; }
        public virtual DbSet<ESPECIE> ESPECIEs { get; set; }
        public virtual DbSet<FACTURA> FACTURAs { get; set; }
        public virtual DbSet<HISTORIA_MEDICA> HISTORIA_MEDICA { get; set; }
        public virtual DbSet<HOSPITALIZACION> HOSPITALIZACIONs { get; set; }
        public virtual DbSet<MASCOTA> MASCOTAs { get; set; }
        public virtual DbSet<MEDICAMENTO> MEDICAMENTOes { get; set; }
        public virtual DbSet<PROPIETARIO> PROPIETARIOs { get; set; }
        public virtual DbSet<SERVICIOS_ADICIONALES> SERVICIOS_ADICIONALES { get; set; }
        public virtual DbSet<TIPO_MEDICAMENTO> TIPO_MEDICAMENTO { get; set; }
        public virtual DbSet<TRATAMIENTO> TRATAMIENTOes { get; set; }
        public virtual DbSet<VETERINARIO> VETERINARIOs { get; set; }
        public virtual DbSet<PERFIL> PERFILs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
    }
}
