//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.DETALLESERVICIOs = new HashSet<DETALLESERVICIO>();
            this.TRATAMIENTOes = new HashSet<TRATAMIENTO>();
        }
    
        public int ID_Factura { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> ID_Mascota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLESERVICIO> DETALLESERVICIOs { get; set; }
        public virtual MASCOTA MASCOTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRATAMIENTO> TRATAMIENTOes { get; set; }
    }
}
