//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPITALIZACION
    {
        public int ID_Hospitalizacion { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> ID_Mascota { get; set; }
    
        public virtual MASCOTA MASCOTA { get; set; }
    }
}
