//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria_REST.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    

    public partial class MEDICAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICAMENTO()
        {
            this.TRATAMIENTOes = new HashSet<TRATAMIENTO>();
        }
    
        public int ID_Medicamento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Dosis { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> ID_TipoMedicamento { get; set; }
    
        public virtual TIPO_MEDICAMENTO TIPO_MEDICAMENTO { get; set; }
        [JsonIgnore] 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRATAMIENTO> TRATAMIENTOes { get; set; }
    }
}
