//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria_REST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRATAMIENTO
    {
        public int ID_Tratamiento { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ID_Factura { get; set; }
        public Nullable<int> ID_Medicamento { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual MEDICAMENTO MEDICAMENTO { get; set; }
    }
}
